# Generated by Django 3.2.10 on 2022-02-15 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsinModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.TextField()),
                ('product_name', models.TextField(blank=True, default='')),
                ('brand', models.TextField(blank=True, default='')),
                ('product_group', models.TextField(blank=True, default='')),
                ('photo_list', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('jan', models.TextField(blank=True, default='', max_length=100)),
                ('category_tree', models.JSONField(blank=True, default={})),
                ('price', models.IntegerField(blank=True, default=0)),
                ('point', models.IntegerField(blank=True, default=0, null=True)),
                ('q10_category', models.TextField(blank=True, default='')),
                ('sell_num', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(blank=True)),
                ('asin_list', models.TextField(blank=True, default='')),
                ('asin_waiting_list', models.TextField(blank=True, default='', null=True)),
                ('asin_getting_list', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('date', models.DateTimeField()),
                ('type', models.TextField()),
                ('input_asin_list', models.TextField(blank=True, default='', null=True)),
                ('success_asin_list', models.TextField(blank=True, default='', null=True)),
                ('cause_list', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Q10BrandCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.TextField()),
                ('code', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Q10ItemsLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('total_asin_list', models.TextField(blank=True, default='', null=True)),
                ('linked_asin_list', models.TextField(blank=True, default='', null=True)),
                ('still_getting', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecordsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(default='', null=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 16, 1, 28, 0, 141175), null=True)),
                ('total_length', models.IntegerField(blank=True, default=0, null=True)),
                ('new_length', models.IntegerField(blank=True, default=0, null=True)),
                ('already_listed', models.BooleanField(blank=True, default=False, null=True)),
                ('asin_list', models.TextField(blank=True, default='', null=True)),
                ('status_text', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(blank=True)),
                ('q10_id', models.TextField(blank=True)),
                ('q10_password', models.TextField(blank=True)),
                ('q10_api', models.TextField(blank=True, default='')),
                ('description_header', models.TextField(blank=True, default='', null=True)),
                ('description_footer', models.TextField(blank=True, default='')),
                ('initial_letter', models.TextField(blank=True, max_length=1)),
                ('delete_or_not', models.BooleanField(blank=True, default=False)),
                ('shipping_code', models.TextField(blank=True, default='')),
                ('stock_num', models.IntegerField(blank=True, default=3)),
                ('photo_num', models.IntegerField(blank=True, default=3)),
                ('maker_name_blacklist', models.TextField(blank=True, default='')),
                ('asin_blacklist', models.TextField(blank=True, default='')),
                ('words_blacklist', models.TextField(blank=True, default='')),
                ('group_black', models.TextField(blank=True, default='')),
                ('min_1', models.IntegerField(blank=True, default=0, null=True)),
                ('max_1', models.IntegerField(blank=True, default=0)),
                ('max_2', models.IntegerField(blank=True, default=0)),
                ('max_3', models.IntegerField(blank=True, default=0)),
                ('max_4', models.IntegerField(blank=True, default=0)),
                ('rieki_1', models.IntegerField(blank=True, default=0)),
                ('rieki_2', models.IntegerField(blank=True, default=0)),
                ('rieki_3', models.IntegerField(blank=True, default=0)),
                ('rieki_4', models.IntegerField(blank=True, default=0)),
                ('kotei_1', models.IntegerField(blank=True, default=0)),
                ('kotei_2', models.IntegerField(blank=True, default=0)),
                ('kotei_3', models.IntegerField(blank=True, default=0)),
                ('kotei_4', models.IntegerField(blank=True, default=0)),
                ('api_ok', models.BooleanField(blank=True, default=False, null=True)),
                ('shop_name', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
