# Generated by Django 4.0 on 2021-12-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_price_revision', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='rieki_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='rieki_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='rieki_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='rieki_4',
            field=models.IntegerField(default=0),
        ),
    ]
