# Generated by Django 4.0 on 2021-12-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_price_revision', '0002_alter_usermodel_rieki_1_alter_usermodel_rieki_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='description_header',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='stock_num',
            field=models.IntegerField(default=3),
        ),
    ]
