# Generated by Django 3.2.10 on 2022-02-16 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_price_revision', '0003_alter_recordsmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordsmodel',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 16, 23, 56, 12, 892307), null=True),
        ),
    ]
