# Generated by Django 4.0 on 2021-12-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_price_revision', '0003_alter_usermodel_description_header_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='description_header',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
