# Generated by Django 3.2.10 on 2022-02-23 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_price_revision', '0004_alter_recordsmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordsmodel',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 23, 15, 17, 39, 441922), null=True),
        ),
    ]
