# Generated by Django 4.0 on 2021-12-15 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_price_revision', '0004_alter_usermodel_description_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='asin_blacklist',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='asin_list',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='delete_or_not',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='description_footer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='group_black',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='initial_letter',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='kaitei_kankaku',
            field=models.TimeField(blank=True, default=datetime.time(2, 0)),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='kotei_1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='kotei_2',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='kotei_3',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='kotei_4',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='maker_name_blacklist',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='max_1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='max_2',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='max_3',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='photo_num',
            field=models.IntegerField(blank=True, default=3),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='q10_id',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='q10_password',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='rieki_1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='rieki_2',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='rieki_3',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='rieki_4',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='shipping_code',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='stock_num',
            field=models.IntegerField(blank=True, default=3),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='words_blacklist',
            field=models.TextField(blank=True, default=''),
        ),
    ]
