# Generated by Django 4.0 on 2021-12-15 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_price_revision', '0005_alter_usermodel_asin_blacklist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsinModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=10)),
                ('product_name', models.TextField(blank=True, default='')),
                ('brand', models.TextField(blank=True, default='')),
                ('product_group', models.TextField(blank=True, default='')),
                ('photo_list', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('jan', models.CharField(default='', max_length=100)),
                ('category_tree', models.TextField(blank=True, default='')),
                ('price', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
