# Generated by Django 3.2.10 on 2022-02-24 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_price_revision', '0005_alter_recordsmodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='asinmodel',
            name='in_black_list',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='recordsmodel',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 24, 22, 12, 46, 365407), null=True),
        ),
    ]
