# Generated by Django 3.2.10 on 2022-02-26 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_price_revision', '0006_auto_20220224_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asinmodel',
            name='in_black_list',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='recordsmodel',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 26, 21, 27, 57, 96089), null=True),
        ),
    ]
