# Generated by Django 4.0 on 2021-12-15 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_price_revision', '0006_asinmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asinmodel',
            name='jan',
            field=models.JSONField(blank=True, default='', max_length=100),
        ),
    ]
