# Generated by Django 4.0 on 2021-12-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_price_revision', '0007_alter_asinmodel_jan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asinmodel',
            name='category_tree',
            field=models.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='asinmodel',
            name='jan',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
    ]
