# Generated by Django 3.2.10 on 2022-02-26 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_price_revision', '0007_auto_20220226_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordsmodel',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 26, 23, 16, 27, 919908), null=True),
        ),
    ]
