# Generated by Django 4.0 on 2021-12-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_price_revision', '0008_alter_asinmodel_category_tree_alter_asinmodel_jan'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='records',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
