# Generated by Django 4.0 on 2021-12-16 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_price_revision', '0009_usermodel_records'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=1000, null=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 17, 1, 31, 45, 260774), null=True)),
                ('total_length', models.IntegerField(blank=True, default=0, null=True)),
                ('new_length', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='records',
        ),
    ]
