# Generated by Django 4.0 on 2021-12-16 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_price_revision', '0011_recordsmodel_already_listed_alter_recordsmodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordsmodel',
            name='asin_list',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='recordsmodel',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 17, 2, 8, 15, 817282), null=True),
        ),
    ]
