# Generated by Django 4.0 on 2021-12-17 22:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_price_revision', '0012_recordsmodel_asin_list_alter_recordsmodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='asin_waiting_list',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='recordsmodel',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 18, 7, 26, 58, 313643), null=True),
        ),
    ]
