# Generated by Django 4.0 on 2021-12-17 22:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_price_revision', '0013_usermodel_asin_waiting_list_alter_recordsmodel_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=1000)),
                ('asin_list', models.TextField(blank=True, default='')),
                ('asin_waiting_list', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='asin_list',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='asin_waiting_list',
        ),
        migrations.AlterField(
            model_name='recordsmodel',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 18, 7, 45, 49, 300219), null=True),
        ),
    ]
