# Generated by Django 3.2.10 on 2022-03-07 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_price_revision', '0018_alter_recordsmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordsmodel',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 8, 1, 2, 29, 413332), null=True),
        ),
    ]
