# Generated by Django 3.2.10 on 2022-01-05 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_price_revision', '0026_auto_20220103_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='logmodel',
            name='cause_list',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='recordsmodel',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 6, 1, 42, 44, 187629), null=True),
        ),
    ]
