# Generated by Django 3.2.10 on 2022-01-05 21:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_price_revision', '0027_auto_20220106_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmodel',
            name='cause_list',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='logmodel',
            name='input_asin_list',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='logmodel',
            name='success_asin_list',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='recordsmodel',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 6, 6, 17, 50, 238883), null=True),
        ),
    ]
