# Generated by Django 3.2.10 on 2022-02-06 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_price_revision', '0034_auto_20220203_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='mega_wari',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='shop_name',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='recordsmodel',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 6, 18, 47, 32, 959540), null=True),
        ),
    ]
