# Generated by Django 3.2.10 on 2022-03-20 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_price_revision', '0036_alter_recordsmodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='asinmodel',
            name='variation_options',
            field=models.JSONField(blank=True, default=[]),
        ),
        migrations.AlterField(
            model_name='recordsmodel',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 21, 4, 45, 45, 939787), null=True),
        ),
    ]
