# Generated by Django 3.2.10 on 2022-03-20 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_price_revision', '0039_auto_20220321_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordsmodel',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 21, 4, 50, 15, 335477), null=True),
        ),
    ]
