# Generated by Django 3.2.9 on 2022-03-22 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_price_revision', '0043_auto_20220321_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingmodel',
            name='no_stock_list',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='selling_list',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='recordsmodel',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 23, 2, 31, 20, 549957), null=True),
        ),
    ]
